/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ar.com.bpba.muleservicemanager;

import ar.com.bpba.muleservicemanager.crearBuild.CrearBuild;
import ar.com.bpba.muleservicemanager.getBuild.GetBuild;
import ar.com.bpba.muleservicemanager.getBuilds.Builds;
import ar.com.bpba.muleservicemanager.getBuilds.Value;
import ar.com.bpba.muleservicemanager.getdetallerelease.DetalleRelease;
import ar.com.bpba.muleservicemanager.getdetallerelease.Task;
import ar.com.bpba.muleservicemanager.getreleases.Releases;
import com.google.gson.Gson;
import java.util.ArrayList;
import java.util.Collection;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.AbstractListModel;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.ListModel;

/**
 *
 * @author P046456
 */
public class ServiceManager extends javax.swing.JFrame {

    /**
     * Creates new form ServiceManager
     */
    public ServiceManager() {
        initComponents();
        //actualizarListas();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel_desa = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField_name = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jTextField_content = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_host = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jTextField_username = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextField_password = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_usuario = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField_clave = new javax.swing.JTextField();
        jTextField_id = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jCheckBox_clave_esVisible = new javax.swing.JCheckBox();
        jButton_guardarDesa = new javax.swing.JButton();
        jButtonActualizarDesa = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jListDesarrollo = new javax.swing.JList<>();
        jPanel_inte = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jListaIntegracion = new javax.swing.JList<>();
        jLabel12 = new javax.swing.JLabel();
        jTextField_name1 = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTextField_content1 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jTextField_host1 = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jTextField_username1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jTextField_password1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextField_usuario1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jTextField_clave1 = new javax.swing.JTextField();
        jTextField_id1 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        jCheckBox_clave_esVisible1 = new javax.swing.JCheckBox();
        jButton_guardarInte = new javax.swing.JButton();
        jButtonActualizarInte = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jTextField_legacyNueva = new javax.swing.JTextField();
        jCheckBox_desarrollo = new javax.swing.JCheckBox();
        jCheckBox_integracion = new javax.swing.JCheckBox();
        jButton_crearLegacy = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        jList_releases = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mule Service Manager");
        setResizable(false);

        jLabel9.setText("Name:");

        jLabel5.setText("Content:");

        jLabel6.setText("Host:");

        jLabel7.setText("Username:");

        jLabel8.setText("Password:");

        jLabel2.setText("Usuario:");

        jLabel3.setText("Clave:");

        jTextField_id.setEditable(false);

        jLabel10.setText("Id:");

        jCheckBox_clave_esVisible.setText("Secreta");

        jButton_guardarDesa.setText("Guardar");
        jButton_guardarDesa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_guardarDesaMouseClicked(evt);
            }
        });

        jButtonActualizarDesa.setText("Actualizar");
        jButtonActualizarDesa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonActualizarDesaMouseClicked(evt);
            }
        });

        jListDesarrollo.setToolTipText("");
        jListDesarrollo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListDesarrolloMouseClicked(evt);
            }
        });
        jListDesarrollo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jListDesarrolloKeyPressed(evt);
            }
        });
        jScrollPane4.setViewportView(jListDesarrollo);

        javax.swing.GroupLayout jPanel_desaLayout = new javax.swing.GroupLayout(jPanel_desa);
        jPanel_desa.setLayout(jPanel_desaLayout);
        jPanel_desaLayout.setHorizontalGroup(
            jPanel_desaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_desaLayout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jButtonActualizarDesa)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel_desaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel_desaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_desaLayout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jButton_guardarDesa)
                        .addGap(38, 38, 38)
                        .addComponent(jCheckBox_clave_esVisible)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_desaLayout.createSequentialGroup()
                        .addGroup(jPanel_desaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_desaLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_clave, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel_desaLayout.createSequentialGroup()
                                .addGroup(jPanel_desaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel_desaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_desaLayout.createSequentialGroup()
                                            .addComponent(jLabel10)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_desaLayout.createSequentialGroup()
                                            .addComponent(jLabel9)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_desaLayout.createSequentialGroup()
                                            .addComponent(jLabel5)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextField_content, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_desaLayout.createSequentialGroup()
                                            .addComponent(jLabel6)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextField_host, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_desaLayout.createSequentialGroup()
                                            .addComponent(jLabel7)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_desaLayout.createSequentialGroup()
                                            .addComponent(jLabel8)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(jTextField_password, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_desaLayout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTextField_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel_desaLayout.setVerticalGroup(
            jPanel_desaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_desaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_desaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_desaLayout.createSequentialGroup()
                        .addGroup(jPanel_desaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_desaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_desaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_content, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_desaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_host, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_desaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextField_username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_desaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_desaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jTextField_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_desaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_clave, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_desaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox_clave_esVisible)
                            .addComponent(jButton_guardarDesa)))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonActualizarDesa)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Legacy Desarrollo", jPanel_desa);

        jListaIntegracion.setName(""); // NOI18N
        jListaIntegracion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jListaIntegracionMouseClicked(evt);
            }
        });
        jListaIntegracion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jListaIntegracionKeyPressed(evt);
            }
        });
        jScrollPane2.setViewportView(jListaIntegracion);

        jLabel12.setText("Name:");

        jLabel13.setText("Content:");

        jLabel14.setText("Host:");

        jLabel15.setText("Username:");

        jLabel16.setText("Password:");

        jLabel4.setText("Usuario:");

        jLabel17.setText("Clave:");

        jTextField_id1.setEditable(false);

        jLabel18.setText("Id:");

        jCheckBox_clave_esVisible1.setText("Secreta");

        jButton_guardarInte.setText("Guardar");
        jButton_guardarInte.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_guardarInteMouseClicked(evt);
            }
        });

        jButtonActualizarInte.setText("Actualizar");

        javax.swing.GroupLayout jPanel_inteLayout = new javax.swing.GroupLayout(jPanel_inte);
        jPanel_inte.setLayout(jPanel_inteLayout);
        jPanel_inteLayout.setHorizontalGroup(
            jPanel_inteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_inteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_inteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_inteLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jButtonActualizarInte)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel_inteLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                        .addGroup(jPanel_inteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_inteLayout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_id1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_inteLayout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_name1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_inteLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_content1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_inteLayout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_host1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_inteLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_username1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_inteLayout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_password1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_inteLayout.createSequentialGroup()
                                .addComponent(jLabel17)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel_inteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel_inteLayout.createSequentialGroup()
                                        .addComponent(jButton_guardarInte)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jCheckBox_clave_esVisible1)
                                        .addGap(29, 29, 29))
                                    .addComponent(jTextField_clave1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_inteLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_usuario1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap())))
        );
        jPanel_inteLayout.setVerticalGroup(
            jPanel_inteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_inteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_inteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_inteLayout.createSequentialGroup()
                        .addGroup(jPanel_inteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_id1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel18))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_inteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_name1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_inteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_content1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_inteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_host1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_inteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(jTextField_username1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_inteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(jTextField_password1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_inteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField_usuario1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel_inteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_clave1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_inteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox_clave_esVisible1)
                            .addComponent(jButton_guardarInte)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonActualizarInte)
                .addContainerGap(21, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Legacy Integracion", jPanel_inte);

        jLabel11.setText("Nombre:");

        jCheckBox_desarrollo.setText("Desarrollo");

        jCheckBox_integracion.setText("Integracion");

        jButton_crearLegacy.setText("Crear");
        jButton_crearLegacy.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton_crearLegacyMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_crearLegacy)
                    .addComponent(jCheckBox_desarrollo)
                    .addComponent(jTextField_legacyNueva, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jCheckBox_integracion))
                .addContainerGap(450, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField_legacyNueva, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox_desarrollo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox_integracion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_crearLegacy)
                .addContainerGap(309, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Crear Build", jPanel1);

        jButton1.setText("Obtener Release");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jScrollPane3.setViewportView(jList_releases);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(221, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Obtener Release", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonActualizarDesaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonActualizarDesaMouseClicked
        actualizarListas();
    }//GEN-LAST:event_jButtonActualizarDesaMouseClicked

    private void actualizarListas() {
        String getBuilds = "http://srvtfsappr01:8080/tfs/An%C3%A1lisis%20y%20Desarrollo/FrontEnd/_apis/build/definitions?api-version=2.2";
        String response = "";
        try {
            response = ConectorTFS.get(getBuilds);
        } catch (Exception ex) {
            Logger.getLogger(ServiceManager.class.getName()).log(Level.SEVERE, null, ex);
        }
        Builds b = new Gson().fromJson(response, Builds.class);
        DefaultListModel modelDesa = new DefaultListModel();
        DefaultListModel modelIntegracion = new DefaultListModel();
        List<Value> values = b.getValue();

        Collections.sort(values, new Comparator<Value>() {
            @Override
            public int compare(final Value object1, final Value object2) {
                return object1.getName().compareTo(object2.getName());
            }
        });

        for (Value v : values) {
            if (v.getName().contains("Legacy")) {
                if (v.getName().contains("desa") && v.getName().contains("3.9")) {
                    modelDesa.addElement(v);
                }
                if (v.getName().contains("inte") && v.getName().contains("3.9")) {
                    modelIntegracion.addElement(v);
                }
            }

        }

        jListDesarrollo.removeAll();
        jListaIntegracion.removeAll();
        jListDesarrollo.setModel(modelDesa);
        jListaIntegracion.setModel(modelIntegracion);

    }

    Object sel;
    private void jListaIntegracionMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListaIntegracionMouseClicked
        sel = jListaIntegracion.getModel().getElementAt(jListaIntegracion.getSelectedIndex());
        obtenerBuildInte(sel);
    }//GEN-LAST:event_jListaIntegracionMouseClicked

    private void jListaIntegracionKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jListaIntegracionKeyPressed
        sel = jListaIntegracion.getModel().getElementAt(jListaIntegracion.getSelectedIndex());
        obtenerBuildInte(sel);
    }//GEN-LAST:event_jListaIntegracionKeyPressed
    GetBuild gbDesa;
    GetBuild gbInte;
    private void jButton_guardarDesaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_guardarDesaMouseClicked

        try {
            String url = "http://srvtfsappr01:8080/tfs/An%C3%A1lisis%20y%20Desarrollo/FrontEnd/_apis/build/definitions/" + gbDesa.getId() + "?api-version=2.2";
            Gson body = new Gson();
            gbDesa.setName(jTextField_name.getText());
            System.out.println("aaa" + jTextField_name.getText());
            gbDesa.getVariables().getUsuario().setValue(jTextField_usuario.getText());
            if (gbDesa.getVariables().getClave().getValue() == null) {
                gbDesa.getVariables().getClave().setValue(null);
            } else {
                gbDesa.getVariables().getClave().setValue(jTextField_clave.getText());
            }
            gbDesa.getBuild().get(1).getInputs().setContents(jTextField_content.getText());
            gbDesa.getBuild().get(1).getInputs().setHost(jTextField_host.getText());
            gbDesa.getBuild().get(1).getInputs().setUsername(jTextField_username.getText());
            gbDesa.getBuild().get(1).getInputs().setPassword(jTextField_password.getText());
            gbDesa.getVariables().getClave().isSecret = jCheckBox_clave_esVisible.isSelected();

            int status = ConectorTFS.put(url, body.toJson(gbDesa));
            actualizarListas();

            JOptionPane.showMessageDialog(this, jTextField_name.getText() + "\nActualizado! Status: " + status);

        } catch (Exception ex) {
            Logger.getLogger(ServiceManager.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_jButton_guardarDesaMouseClicked

    private void jButton_crearLegacyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_crearLegacyMouseClicked
        // TODO add your handling code here:
        String url = "http://srvtfsappr01:8080/tfs/An%C3%A1lisis%20y%20Desarrollo/FrontEnd/_apis/build/definitions?api-version=2.2";
        int statusDesa = 0;
        int statusInte = 0;
        String mensajeDesa = "";
        String mensajeInte = "";

        if (jCheckBox_desarrollo.isSelected()) {
            String variableServerIp = "10.1.13.202";
            String variableBranch = "desarrollo";
            String variableIntegracionContinua = "+refs/heads/desarrollo";
            String variableDisplayName = "SFTP " + variableServerIp;
            String variableDefaultBranch = "refs/heads/" + variableBranch;
            String variableNombreLegacy = "MuleLegacy" + jTextField_legacyNueva.getText();

            String crearBuild = Variables.crearBuild;
            crearBuild = crearBuild.replace("variableServerIp", variableServerIp);
            crearBuild = crearBuild.replace("variableBranch", variableBranch);
            crearBuild = crearBuild.replace("variableDisplayName", variableDisplayName);
            crearBuild = crearBuild.replace("variableDefaultBranch", variableDefaultBranch);
            crearBuild = crearBuild.replace("variableNombreLegacy", variableNombreLegacy);
            crearBuild = crearBuild.replace("variableIntegracionContinua", variableIntegracionContinua);

            try {
                statusDesa = ConectorTFS.post(crearBuild, url);
                mensajeDesa = variableNombreLegacy + " status: " + statusDesa;
            } catch (Exception ex) {
                Logger.getLogger(ServiceManager.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
        if (jCheckBox_integracion.isSelected()) {
            String variableServerIp = "10.1.13.204";
            String variableBranch = "integracion";
            String variableIntegracionContinua = "+refs/heads/integracion";
            String variableDisplayName = "SFTP " + variableServerIp;
            String variableDefaultBranch = "refs/heads/" + variableBranch;
            String variableNombreLegacy = "MuleLegacy" + jTextField_legacyNueva.getText();

            String crearBuild = Variables.crearBuild;
            crearBuild = crearBuild.replace("variableServerIp", variableServerIp);
            crearBuild = crearBuild.replace("variableBranch", variableBranch);
            crearBuild = crearBuild.replace("variableDisplayName", variableDisplayName);
            crearBuild = crearBuild.replace("variableDefaultBranch", variableDefaultBranch);
            crearBuild = crearBuild.replace("variableNombreLegacy", variableNombreLegacy);
            crearBuild = crearBuild.replace("variableIntegracionContinua", variableIntegracionContinua);

            try {
                statusInte = ConectorTFS.post(crearBuild, url);
                mensajeInte = variableNombreLegacy + " status: " + statusInte;
            } catch (Exception ex) {
                Logger.getLogger(ServiceManager.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

        JOptionPane.showMessageDialog(this, mensajeDesa + "\n" + mensajeInte);


    }//GEN-LAST:event_jButton_crearLegacyMouseClicked

    private void jButton_guardarInteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton_guardarInteMouseClicked

        try {
            String url = "http://srvtfsappr01:8080/tfs/An%C3%A1lisis%20y%20Desarrollo/FrontEnd/_apis/build/definitions/" + gbInte.getId() + "?api-version=2.2";
            Gson body = new Gson();
            gbInte.setName(jTextField_name1.getText());
            gbInte.getVariables().getUsuario().setValue(jTextField_usuario1.getText());
            if (gbInte.getVariables().getClave().getValue() == null) {
                gbInte.getVariables().getClave().setValue(null);
            } else {
                gbInte.getVariables().getClave().setValue(jTextField_clave1.getText());
            }
            gbInte.getBuild().get(1).getInputs().setContents(jTextField_content1.getText());
            gbInte.getBuild().get(1).getInputs().setHost(jTextField_host1.getText());
            gbInte.getBuild().get(1).getInputs().setUsername(jTextField_username1.getText());
            gbInte.getBuild().get(1).getInputs().setPassword(jTextField_password1.getText());
            gbInte.getVariables().getClave().isSecret = jCheckBox_clave_esVisible1.isSelected();

            int status = ConectorTFS.put(url, body.toJson(gbInte));
            actualizarListas();

            JOptionPane.showMessageDialog(this, jTextField_name1.getText() + "\nActualizado! Status: " + status);

        } catch (Exception ex) {
            Logger.getLogger(ServiceManager.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButton_guardarInteMouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        ObtenerAllReleases r = new ObtenerAllReleases();
        Releases resultado = r.obtenerAllReleases();
        List<ar.com.bpba.muleservicemanager.getreleases.Value> listaIdReleases = r.obtenerAllReleases().getValue();
        int cantidad = resultado.getCount();
        DefaultListModel listaReleases = new DefaultListModel();
        for (ar.com.bpba.muleservicemanager.getreleases.Value tmp : listaIdReleases) {
            int count = 0;
            int maxTries = 3;
            while (true) {
                try {
                    System.out.println("Cantidad restante: " + cantidad-- + " | id actual: " + tmp.getId());
                    ObtenerRelease or = new ObtenerRelease();
                    DetalleRelease res = or.obtenerDetalleRelease(tmp.getId() + "");
                    ArrayList<Task> tareas = res.getEnvironments().get(0).getDeployStep().getTasks();
                    for (Task tmp2 : tareas) {
                        if (tmp2.getInputs().getHost() != null) {
                            if (tmp2.getInputs().getHost().equals("10.1.13.125")) {
                                listaReleases.addElement(tmp);
                            }
                        }

                    }

                    break;
                } catch (Exception e) {
                    // handle exception
                    System.out.println("Fallo: " + count);
                    try {
                        Thread.sleep(2000);
                    } catch (InterruptedException ex) {
                        Logger.getLogger(ServiceManager.class.getName()).log(Level.SEVERE, null, ex);
                    }
                    if (++count == maxTries) {
                        throw e;
                    }
                }
            }

        }
        jList_releases.setModel(listaReleases);

    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
   
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jListDesarrolloMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jListDesarrolloMouseClicked
        // TODO add your handling code here:
         sel = jListDesarrollo.getModel().getElementAt(jListDesarrollo.getSelectedIndex());
        obtenerBuildDesa(sel);
    }//GEN-LAST:event_jListDesarrolloMouseClicked

    private void jListDesarrolloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jListDesarrolloKeyPressed
        // TODO add your handling code here:
         sel = jListDesarrollo.getModel().getElementAt(jListDesarrollo.getSelectedIndex());
        obtenerBuildDesa(sel);
    }//GEN-LAST:event_jListDesarrolloKeyPressed

    private GetBuild obtenerBuildDesa(Object sel) {

        ObtenerBuild ob = new ObtenerBuild();
        ob.obtenerBuild(sel);

        gbDesa = ob.obtenerBuild(sel);

        jTextField_usuario.setText(gbDesa.getVariables().getUsuario().getValue());
        jTextField_clave.setText(gbDesa.getVariables().getClave().getValue() + "");
        jTextField_content.setText(gbDesa.getBuild().get(1).getInputs().getContents());
        jTextField_host.setText(gbDesa.getBuild().get(1).getInputs().getHost());
        jTextField_username.setText(gbDesa.getBuild().get(1).getInputs().getUsername());
        jTextField_password.setText(gbDesa.getBuild().get(1).getInputs().getPassword());
        jTextField_id.setText("" + gbDesa.getId());
        jTextField_name.setText(gbDesa.getName());
        jCheckBox_clave_esVisible.setSelected(gbDesa.getVariables().getClave().isSecret);
        return gbDesa;

    }

    private GetBuild obtenerBuildInte(Object sel) {

        ObtenerBuild ob = new ObtenerBuild();
        ob.obtenerBuild(sel);

        gbInte = ob.obtenerBuild(sel);

        jTextField_usuario1.setText(gbInte.getVariables().getUsuario().getValue());
        jTextField_clave1.setText(gbInte.getVariables().getClave().getValue() + "");
        jTextField_content1.setText(gbInte.getBuild().get(1).getInputs().getContents());
        jTextField_host1.setText(gbInte.getBuild().get(1).getInputs().getHost());
        jTextField_username1.setText(gbInte.getBuild().get(1).getInputs().getUsername());
        jTextField_password1.setText(gbInte.getBuild().get(1).getInputs().getPassword());
        jTextField_id1.setText("" + gbInte.getId());
        jTextField_name1.setText(gbInte.getName());
        jCheckBox_clave_esVisible1.setSelected(gbInte.getVariables().getClave().isSecret);

        return gbInte;
    }
    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonActualizarDesa;
    private javax.swing.JButton jButtonActualizarInte;
    private javax.swing.JButton jButton_crearLegacy;
    private javax.swing.JButton jButton_guardarDesa;
    private javax.swing.JButton jButton_guardarInte;
    private javax.swing.JCheckBox jCheckBox_clave_esVisible;
    private javax.swing.JCheckBox jCheckBox_clave_esVisible1;
    private javax.swing.JCheckBox jCheckBox_desarrollo;
    private javax.swing.JCheckBox jCheckBox_integracion;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jListDesarrollo;
    private javax.swing.JList<String> jList_releases;
    private javax.swing.JList<String> jListaIntegracion;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel_desa;
    private javax.swing.JPanel jPanel_inte;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField_clave;
    private javax.swing.JTextField jTextField_clave1;
    private javax.swing.JTextField jTextField_content;
    private javax.swing.JTextField jTextField_content1;
    private javax.swing.JTextField jTextField_host;
    private javax.swing.JTextField jTextField_host1;
    private javax.swing.JTextField jTextField_id;
    private javax.swing.JTextField jTextField_id1;
    private javax.swing.JTextField jTextField_legacyNueva;
    private javax.swing.JTextField jTextField_name;
    private javax.swing.JTextField jTextField_name1;
    private javax.swing.JTextField jTextField_password;
    private javax.swing.JTextField jTextField_password1;
    private javax.swing.JTextField jTextField_username;
    private javax.swing.JTextField jTextField_username1;
    private javax.swing.JTextField jTextField_usuario;
    private javax.swing.JTextField jTextField_usuario1;
    // End of variables declaration//GEN-END:variables
}
